[build-system]
requires = ["setuptools>=42","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "simple_search"
version = "0.0.0"

[project.scripts]
run-reports = "simple_search.reports.run_reports:main"

[tool.pytest.ini_options]
pythonpath = ["."]
